namespace ImmigrationZucc.Core.Enums
{
    public enum StreamType
    {
        ON_FOREIGNWORKER,
        ON_INTERNATIONALSTUDENT,
        ON_INDEMANDSKILLS,
        ON_MASTERSGRADUATE,
        ON_PHDGRADUATE,
        ON_EXPRESSENTRYFRENCHSPEAKINGSKILLEDWORKER,
        ON_EXPRESSENTRYHUMANCAPITALPRIORITIES,
        ON_EXPRESSENTRYSKILLEDTRADES,
        ON_ENTREPRENEUR
    }
}
